import { Injectable } from '@nestjs/common';
import { SystemModuleDoc } from '../interfaces/system-docs.interface';

@Injectable()
export class SystemDocsService {
  private readonly modulesDoc: SystemModuleDoc[] = [
    {
      id: 'db-pagination-benchmark',
      phase: 'Phase 1',
      moduleCode: 'module-1.1',
      title: 'Pagination Benchmark (10M Rows)',
      badge: 'Database Optimization',
      overview: 'So sánh hiệu năng phân trang trên tập dữ liệu 10 triệu dòng giữa Offset Sequential Scan O(N) và Keyset Cursor Index Seek O(1).',
      naiveStrategy: {
        description: 'Naive Offset (OFFSET 5,000,000 LIMIT 20): Đọc và bỏ qua 5 triệu dòng trước khi trả về kết quả.',
        endpoint: '/api/v1/db-pagination/naive/users?page=250000&limit=20',
        method: 'GET',
        drawback: 'Latency tăng tuyến tính O(N), làm sập DB khi offset sâu.',
      },
      optimizedStrategy: {
        description: 'Optimized Keyset Cursor (WHERE id > 5000000 LIMIT 20): Nhảy thẳng tới vị trí B-Tree Index Seek.',
        endpoint: '/api/v1/db-pagination/optimized/users/keyset?cursor=5000000&limit=20',
        method: 'GET',
        advantage: 'Tốc độ O(1) hằng số < 5ms dù ở trang thứ 1 hay trang thứ 1 triệu.',
      },
      flowSteps: [
        { stepNumber: 1, title: 'Client Request', description: 'Client gửi cursor ID của bản ghi cuối trang trước', component: 'Web/Postman' },
        { stepNumber: 2, title: 'B-Tree Index Seek', description: 'Postgres thực hiện B-Tree seek WHERE id > cursor', component: 'PostgreSQL Engine' },
        { stepNumber: 3, title: 'Fetch Heap Rows', description: 'Đọc chính xác 20 bản ghi tiếp theo từ đĩa', component: 'PostgreSQL Heap' },
        { stepNumber: 4, title: 'Response Delivery', description: 'Trả về dữ liệu kèm nextCursor cho trang kế', component: 'NestJS Controller' },
      ],
      benchmarkResult: {
        naiveMetric: '1,418.04 ms (Trang 250,000)',
        optimizedMetric: '3.14 ms',
        improvement: 'Nhanh hơn 450x lần',
      },
      curlSnippet: 'curl -s "http://localhost:3000/api/v1/db-pagination/optimized/users/keyset?cursor=5000000&limit=20"',
    },
    {
      id: 'db-sargable-parameter-binding',
      phase: 'Phase 1',
      moduleCode: 'module-1.2',
      title: 'Sargable Queries & Parameter Plan Caching',
      badge: 'Database Optimization',
      overview: 'Kỹ thuật viết câu lệnh SQL Sargable để tận dụng B-Tree Index và Prepared Statement Plan Caching.',
      naiveStrategy: {
        description: 'Bọc cột trong hàm DATE(created_at) = $1 làm vô hiệu hóa B-Tree Index Range Scan.',
        endpoint: '/api/v1/db-sargable/naive/search-date',
        method: 'POST',
        samplePayload: { date: '2026-08-01' },
        drawback: 'Bắt buộc Postgres phải quét toàn bộ bảng (Seq Scan).',
      },
      optimizedStrategy: {
        description: 'Truy vấn Sargable created_at >= $1 AND created_at < $2 tận dụng B-Tree Index Range Scan.',
        endpoint: '/api/v1/db-sargable/optimized/search-date',
        method: 'POST',
        samplePayload: { startDate: '2026-08-01', endDate: '2026-08-02' },
        advantage: 'Chỉ quét các block dữ liệu trong dải Index Range Scan.',
      },
      flowSteps: [
        { stepNumber: 1, title: 'Query Parsing', description: 'Parse câu lệnh SQL chứa tham số định danh $1, $2', component: 'TypeORM / Raw SQL' },
        { stepNumber: 2, title: 'Plan Cache Lookup', description: 'Postgres kiểm tra Prepared Statement Execution Plan', component: 'PG Planner' },
        { stepNumber: 3, title: 'Index Range Seeking', description: 'Tìm kiếm chính xác các nút lá B-Tree', component: 'PostgreSQL B-Tree' },
      ],
      benchmarkResult: {
        naiveMetric: '145.0 ms',
        optimizedMetric: '0.8 ms',
        improvement: 'Nhanh hơn 180x lần',
      },
      curlSnippet: 'curl -X POST http://localhost:3000/api/v1/db-sargable/optimized/search-date -H "Content-Type: application/json" -d \'{"startDate":"2026-08-01","endDate":"2026-08-02"}\'',
    },
    {
      id: 'db-advanced-indexing-explain',
      phase: 'Phase 1',
      moduleCode: 'module-1.3',
      title: 'Advanced Indexing & EXPLAIN (10M Orders)',
      badge: 'Database Optimization',
      overview: 'Phân tích câu lệnh bằng EXPLAIN ANALYZE với B-Tree Composite Index (Leftmost Prefix), Partial Index và GIN JSONB Index trên 10 triệu đơn hàng.',
      naiveStrategy: {
        description: 'Quét toàn bộ 10 triệu bản ghi JSONB bằng toán tử chuỗi.',
        endpoint: '/api/v1/db-indexing/naive/leftmost',
        method: 'POST',
        drawback: 'Tốn CPU & Memory IO để giải mã JSON thô.',
      },
      optimizedStrategy: {
        description: 'Dùng GIN Index (metadata @> $1) và Partial Index cho trạng thái PENDING.',
        endpoint: '/api/v1/db-indexing/optimized/gin-jsonb?category=ELECTRONICS',
        method: 'GET',
        advantage: 'Truy vấn JSONB sub-millisecond trên 10 triệu bản ghi.',
      },
      flowSteps: [
        { stepNumber: 1, title: 'JSONB Containment', description: 'Áp dụng toán tử containment @> trên cột metadata', component: 'PostgreSQL GIN' },
        { stepNumber: 2, title: 'Bitmap Index Scan', description: 'Lấy Bitmap các Heap Tuple chứa key JSON matching', component: 'PostgreSQL Engine' },
        { stepNumber: 3, title: 'Recheck Heap', description: 'Đọc chính xác các block bộ nhớ cần thiết', component: 'PostgreSQL Heap' },
      ],
      benchmarkResult: {
        naiveMetric: '220.0 ms',
        optimizedMetric: '0.114 ms',
        improvement: 'Nhanh hơn 1,900x lần',
      },
      curlSnippet: 'curl -s "http://localhost:3000/api/v1/db-indexing/optimized/gin-jsonb?category=ELECTRONICS"',
    },
    {
      id: 'db-window-functions-materialized-views',
      phase: 'Phase 1',
      moduleCode: 'module-1.4',
      title: 'Window Functions & Concurrent Materialized Views',
      badge: 'Database Optimization',
      overview: 'Tính toán phân hạng ROW_NUMBER()/RANK() trực tiếp trong SQL và sử dụng Concurrent Materialized View cho báo cáo Analytics.',
      naiveStrategy: {
        description: 'Kéo hàng triệu dòng về Node.js RAM để tính toán bằng hàm `.sort()` / `.filter()`.',
        endpoint: '/api/v1/db-window-mview/naive/analytics',
        method: 'GET',
        drawback: 'Tràn bộ nhớ V8 RAM, làm treo Event Loop.',
      },
      optimizedStrategy: {
        description: 'Tính toán trong SQL Window Functions & Refresh Materialized View Concurrently.',
        endpoint: '/api/v1/db-window-mview/optimized/analytics',
        method: 'GET',
        advantage: 'Không block đọc dữ liệu khi làm mới báo cáo.',
      },
      flowSteps: [
        { stepNumber: 1, title: 'SQL Window Processing', description: 'Tính ROW_NUMBER() OVER (PARTITION BY category)', component: 'PostgreSQL Query Engine' },
        { stepNumber: 2, title: 'Concurrent View Refresh', description: 'REFRESH MATERIALIZED VIEW CONCURRENTLY', component: 'PostgreSQL Background Worker' },
      ],
      benchmarkResult: {
        naiveMetric: '650.0 ms',
        optimizedMetric: '3.5 ms',
        improvement: 'Nhanh hơn 185x lần',
      },
      curlSnippet: 'curl -s "http://localhost:3000/api/v1/db-window-mview/optimized/analytics"',
    },
    {
      id: 'db-ledger-pattern',
      phase: 'Phase 1',
      moduleCode: 'module-1.5',
      title: 'Immutable Ledger Pattern (SHA-256 Chaining)',
      badge: 'Financial Integrity',
      overview: 'Mô hình Sổ cái Tài chính Bất biến (Append-only Ledger) sử dụng chuỗi băm Cryptographic SHA-256 Hash Chaining.',
      naiveStrategy: {
        description: 'Cập nhật trực tiếp số dư `UPDATE balance = balance + X` (dễ bị ghi đè hoặc chỉnh sửa ngầm).',
        endpoint: '/api/v1/db-ledger/naive/transfer',
        method: 'POST',
        drawback: 'Không thể truy vết lịch sử gian lận nếu ai đó sửa DB.',
      },
      optimizedStrategy: {
        description: 'Ghi giao dịch mới nối chuỗi Hash `current_hash = SHA256(prev_hash + tx_data)`.',
        endpoint: '/api/v1/db-ledger/optimized/transfer',
        method: 'POST',
        samplePayload: { fromAccountId: 'ACC_1001', toAccountId: 'ACC_1002', amount: 250 },
        advantage: 'Phát hiện lập tức mọi hành vi sửa đổi dữ liệu quá khứ.',
      },
      flowSteps: [
        { stepNumber: 1, title: 'Fetch Previous Hash', description: 'Lấy SHA-256 hash của giao dịch gần nhất', component: 'Ledger Engine' },
        { stepNumber: 2, title: 'Calculate SHA-256', description: 'Băm dữ liệu giao dịch mới kết hợp previousHash', component: 'Crypto Service' },
        { stepNumber: 3, title: 'Append Entry', description: 'Ghi duy nhất lệnh INSERT (Append-only)', component: 'PostgreSQL Transaction' },
      ],
      benchmarkResult: {
        naiveMetric: 'Auditability: 0%',
        optimizedMetric: 'Integrity: 100% Guaranteed',
        improvement: 'Cryptographic Integrity Verification',
      },
      curlSnippet: 'curl -X POST http://localhost:3000/api/v1/db-ledger/optimized/transfer -H "Content-Type: application/json" -d \'{"fromAccountId":"ACC_1001","toAccountId":"ACC_1002","amount":250}\'',
    },
    {
      id: 'concurrency-locking-strategies',
      phase: 'Phase 2',
      moduleCode: 'module-2.1',
      title: 'Concurrency Control & Advisory Locks',
      badge: 'High Concurrency',
      overview: 'Xử lý xung đột tranh chấp dữ liệu bằng Optimistic OCC Versioning, Pessimistic FOR UPDATE, và Postgres Advisory Locks.',
      naiveStrategy: {
        description: 'Đọc stock -> Trừ stock -> Ghi đè stock không qua khóa kiểm soát.',
        endpoint: '/api/v1/concurrency-locking/naive/deduct',
        method: 'POST',
        drawback: 'Gây lỗi Lost Updates (trừ thiếu kho khi có nhiều CCU).',
      },
      optimizedStrategy: {
        description: 'Sử dụng Optimistic OCC (`version = version + 1`) hoặc Postgres Advisory Lock (`pg_advisory_xact_lock`).',
        endpoint: '/api/v1/concurrency-locking/optimized/deduct/optimistic',
        method: 'POST',
        samplePayload: { productId: 1, quantity: 1 },
        advantage: 'Đảm bảo 100% chính xác tồn kho dưới tải cao.',
      },
      flowSteps: [
        { stepNumber: 1, title: 'Acquire Advisory Lock', description: 'Gọi pg_advisory_xact_lock(hashtext(product_id))', component: 'PostgreSQL Lock Manager' },
        { stepNumber: 2, title: 'Atomic Inventory Check', description: 'Kiểm tra stock >= quantity trong Transaction', component: 'TypeORM Transaction' },
        { stepNumber: 3, title: 'Commit & Auto Release', description: 'Commit transaction và tự giải phóng lock', component: 'PostgreSQL Engine' },
      ],
      benchmarkResult: {
        naiveMetric: 'Data Corruption Under Load',
        optimizedMetric: 'Zero Race Conditions',
        improvement: '100% Stock Consistency',
      },
      curlSnippet: 'curl -X POST http://localhost:3000/api/v1/concurrency-locking/optimized/deduct/optimistic -H "Content-Type: application/json" -d \'{"productId":1,"quantity":1}\'',
    },
    {
      id: 'redis-lua-rate-limit-flashsale',
      phase: 'Phase 2',
      moduleCode: 'module-2.2',
      title: 'Redis Lua Rate Limiting & Flash Sale (25k RPS)',
      badge: 'High Concurrency',
      overview: 'Xử lý giới hạn tần suất (Sliding Window Log) và trừ tồn kho Flash Sale siêu tốc bằng Redis Lua Script nguyên tử.',
      naiveStrategy: {
        description: 'Thực hiện nhiều câu lệnh Redis riêng lẻ (GET -> CHECK -> DECRBY).',
        endpoint: '/api/v1/redis-lua/naive/flash-sale',
        method: 'POST',
        drawback: 'Xảy ra Race Condition giữa các lệnh cURL concurrent.',
      },
      optimizedStrategy: {
        description: 'Đóng gói toàn bộ logic vào 1 đoạn Redis Lua Script đơn (Atomic Single-Threaded Execution).',
        endpoint: '/api/v1/redis-lua/optimized/flash-sale',
        method: 'POST',
        samplePayload: { productId: 'FLASH_IPHONE_16', quantity: 1 },
        advantage: 'Đạt 25,000 RPS với 0% bán lố (Zero Overselling).',
      },
      flowSteps: [
        { stepNumber: 1, title: 'EVALSHA Lua Script', description: 'Gửi script SHA hash tới Redis server', component: 'ioredis Client' },
        { stepNumber: 2, title: 'Single-Threaded Execution', description: 'Redis thực thi câu lệnh Lua nguyên tử không bị ngắt', component: 'Redis Engine' },
        { stepNumber: 3, title: 'Atomic Stock Decr', description: 'DECRBY và kiểm tra số dư > 0 trong 1 chu kỳ', component: 'Redis In-Memory Key' },
      ],
      benchmarkResult: {
        naiveMetric: '200 RPS (Risk of Overselling)',
        optimizedMetric: '25,000 RPS',
        improvement: 'Tăng 125x lần Throughput',
      },
      curlSnippet: 'curl -X POST http://localhost:3000/api/v1/redis-lua/optimized/flash-sale -H "Content-Type: application/json" -d \'{"productId":"FLASH_IPHONE_16","quantity":1}\'',
    },
    {
      id: 'idempotency-connection-pooling',
      phase: 'Phase 2',
      moduleCode: 'module-2.3',
      title: 'Idempotency Key & PgBouncer Connection Pool',
      badge: 'High Concurrency',
      overview: 'Lọc trùng lặp request giao dịch bằng Header `x-idempotency-key` kết hợp Redis SET NX EX và tối ưu DB Connection Pool.',
      naiveStrategy: {
        description: 'Xử lý request trực tiếp không có cơ chế chặn trùng lặp.',
        endpoint: '/api/v1/idempotency-pool/naive/payment',
        method: 'POST',
        drawback: 'Nguy cơ quẹt thẻ 2 lần khi người dùng bấm liên tục.',
      },
      optimizedStrategy: {
        description: 'Kiểm tra `x-idempotency-key` trên Redis SET NX. Trả về Cache HIT sub-millisecond cho request lặp.',
        endpoint: '/api/v1/idempotency-pool/optimized/payment',
        method: 'POST',
        samplePayload: { accountId: 'ACC_1001', amount: 500 },
        advantage: 'Chống quẹt thẻ trùng lặp 100% và tiết kiệm tài nguyên DB.',
      },
      flowSteps: [
        { stepNumber: 1, title: 'Idempotency Header Check', description: 'Đọc header x-idempotency-key từ HTTP request', component: 'Idempotency Filter' },
        { stepNumber: 2, title: 'Atomic Redis SET NX', description: 'Khóa key trên Redis: SET key timestamp NX EX 86400', component: 'Redis Store' },
        { stepNumber: 3, title: 'Return Cached Response', description: 'Nếu key đã tồn tại, trả về kết quả cũ kèm header x-cache: HIT', component: 'Cache Guard' },
      ],
      benchmarkResult: {
        naiveMetric: 'Duplicate Payment Risks',
        optimizedMetric: '0.8 ms (Cache HIT)',
        improvement: 'Nhanh hơn 115x lần cho request trùng',
      },
      curlSnippet: 'curl -X POST http://localhost:3000/api/v1/idempotency-pool/optimized/payment -H "Content-Type: application/json" -H "x-idempotency-key: PAY_9981" -d \'{"accountId":"ACC_1001","amount":500}\'',
    },
    {
      id: 'kafka-partitioning-consumer-groups',
      phase: 'Phase 3',
      moduleCode: 'module-3.1',
      title: 'Kafka Partition Routing & Consumer Groups',
      badge: 'Event-Driven Architecture',
      overview: 'Điều hướng Message theo Partition Key (MurmurHash2) đảm bảo thứ tự xử lý tuyệt đối và quản lý Consumer Group Offsets.',
      naiveStrategy: {
        description: 'Gửi message không kèm Key (Round-robin partition distribution).',
        endpoint: '/api/v1/kafka-core/naive/produce',
        method: 'POST',
        drawback: 'Cùng 1 đơn hàng bị xử lý sai thứ tự (Ví dụ: CANCEL đến trước CREATE).',
      },
      optimizedStrategy: {
        description: 'Gửi message kèm `key = orderId` để luôn lọt vào cùng 1 Kafka Partition.',
        endpoint: '/api/v1/kafka-core/optimized/produce',
        method: 'POST',
        samplePayload: { orderId: 'ORD_9910', eventType: 'ORDER_CREATED', payload: { amount: 150 } },
        advantage: 'Đảm bảo thứ tự thời gian 100% cho mỗi đơn hàng.',
      },
      flowSteps: [
        { stepNumber: 1, title: 'Partition Key Hashing', description: 'Tính Hash(orderId) % numPartitions', component: 'Kafka Producer' },
        { stepNumber: 2, title: 'Sequential Append', description: 'Ghi nối tiếp vào đuôi Log Partition chỉ định', component: 'Kafka Broker' },
        { stepNumber: 3, title: 'Single Worker Consumption', description: 'Consumer thuộc Group xử lý tuần tự theo Offset', component: 'Kafka Consumer Group' },
      ],
      benchmarkResult: {
        naiveMetric: 'Unordered Message Risk',
        optimizedMetric: 'Strict Order Guarantee',
        improvement: '10,000 msg/sec Ordered Ingestion',
      },
      curlSnippet: 'curl -X POST http://localhost:3000/api/v1/kafka-core/optimized/produce -H "Content-Type: application/json" -d \'{"orderId":"ORD_9910","eventType":"ORDER_CREATED","payload":{"amount":150}}\'',
    },
    {
      id: 'transactional-outbox-pattern',
      phase: 'Phase 3',
      moduleCode: 'module-3.2',
      title: 'Transactional Outbox Pattern (Dual-Write Protection)',
      badge: 'Event-Driven Architecture',
      overview: 'Giải quyết triệt để sự cố mất dữ liệu khi ghi đồng thời vào DB và Kafka (Dual-Write Problem) bằng mô hình Transactional Outbox & CDC Relay Worker.',
      naiveStrategy: {
        description: 'Ghi DB xong gọi trực tiếp Kafka Producer (`await kafka.send()`).',
        endpoint: '/api/v1/outbox-pattern/naive/create-order',
        method: 'POST',
        drawback: 'Nếu Kafka sập hoặc nghẽn mạng, DB đã ghi nhưng Message bị mất vĩnh viễn.',
      },
      optimizedStrategy: {
        description: 'Lưu Order + Event vào Outbox Table trong cùng 1 DB Transaction nguyên tử. CDC Worker sẽ quét và gửi sang Kafka ngầm.',
        endpoint: '/api/v1/outbox-pattern/optimized/create-order',
        method: 'POST',
        samplePayload: { customerId: 'CUST_88', totalAmount: 499.99, items: ['iPhone 16 Pro'] },
        advantage: 'Đảm bảo 100% dữ liệu đồng bộ (At-Least-Once Delivery).',
      },
      flowSteps: [
        { stepNumber: 1, title: 'Atomic DB Transaction', description: 'BEGIN; INSERT INTO orders; INSERT INTO outbox_events; COMMIT;', component: 'PostgreSQL Transaction' },
        { stepNumber: 2, title: 'CDC Relay Poller', description: 'Relay Worker quét SELECT * FROM outbox_events FOR UPDATE SKIP LOCKED', component: 'CDC Worker' },
        { stepNumber: 3, title: 'Publish to Broker', description: 'Gửi event sang Kafka và cập nhật status = PROCESSED', component: 'Kafka Broker' },
      ],
      benchmarkResult: {
        naiveMetric: 'Dual-Write Data Loss Risk',
        optimizedMetric: '100% Guaranteed Delivery',
        improvement: 'At-Least-Once Consistency',
      },
      curlSnippet: 'curl -X POST http://localhost:3000/api/v1/outbox-pattern/optimized/create-order -H "Content-Type: application/json" -d \'{"customerId":"CUST_88","totalAmount":499.99,"items":["iPhone 16 Pro"]}\'',
    },
    {
      id: 'messaging-head-to-head',
      phase: 'Phase 3',
      moduleCode: 'module-3.3',
      title: 'Messaging Head-to-Head (Kafka vs RabbitMQ vs BullMQ)',
      badge: 'Event-Driven Architecture',
      overview: 'So sánh trực tiếp Throughput, Latency, và khả năng Replay giữa Apache Kafka, RabbitMQ AMQP, và BullMQ Redis Queue.',
      naiveStrategy: {
        description: 'Sử dụng 1 hàng chờ đơn lẻ cho mọi loại công việc (blocking heavy jobs).',
        endpoint: '/api/v1/messaging-comparison/naive/publish',
        method: 'POST',
        drawback: 'Nghẽn hàng chờ khi có tác vụ nặng.',
      },
      optimizedStrategy: {
        description: 'Định tuyến công việc dựa trên đặc tính: Kafka (Log Streaming 100k+ msg/s), RabbitMQ (Complex AMQP Routing & DLQ), BullMQ (Priority & Delay jobs).',
        endpoint: '/api/v1/messaging-comparison/optimized/benchmark',
        method: 'POST',
        samplePayload: { totalMessages: 1000, targetBroker: 'KAFKA' },
        advantage: 'Tối ưu hóa kiến trúc nhắn tin theo đúng nhu cầu nghiệp vụ.',
      },
      flowSteps: [
        { stepNumber: 1, title: 'Broker Matrix Routing', description: 'Phân loại bài toán: High Throughput (Kafka) vs Complex Routing (RabbitMQ) vs Delayed Jobs (BullMQ)', component: 'Messaging Router' },
        { stepNumber: 2, title: 'Parallel Execution', description: 'Bơm dữ liệu đồng thời vào 3 broker để đo P95 Latency', component: 'Benchmark Engine' },
      ],
      benchmarkResult: {
        naiveMetric: '150 msg/sec',
        optimizedMetric: '18,000 msg/sec (Kafka)',
        improvement: 'Tăng 120x lần Throughput',
      },
      curlSnippet: 'curl -X POST http://localhost:3000/api/v1/messaging-comparison/optimized/benchmark -H "Content-Type: application/json" -d \'{"totalMessages":1000,"targetBroker":"KAFKA"}\'',
    },
    {
      id: 'traffic-engineering-feature-flags',
      phase: 'Phase 4',
      moduleCode: 'module-4.1',
      title: 'Dynamic Feature Flags & Shadow Traffic (Dark Launching)',
      badge: 'Traffic Engineering',
      overview: 'Điều phối Traffic không cần Redeploy server bằng Dynamic Redis Feature Flags (Canary Rollout) và nhân bản request thử nghiệm ngầm (Shadow Traffic).',
      naiveStrategy: {
        description: 'Hardcode biến feature bọc bằng hàm `if/else` trong mã nguồn.',
        endpoint: '/api/v1/traffic-engineering/naive/evaluate',
        method: 'POST',
        drawback: 'Muốn bật/tắt hoặc đổi % rollout bắt buộc phải Rebuild & Redeploy lại toàn bộ hệ thống.',
      },
      optimizedStrategy: {
        description: 'Tải quy tắc từ Redis (sub-5ms) + băm `userId` thành 100 bucket nhất quán + Mirror request ngầm qua `setImmediate`.',
        endpoint: '/api/v1/traffic-engineering/optimized/evaluate',
        method: 'POST',
        samplePayload: { flagName: 'NEW_CHECKOUT_V2', userId: 'USER_5521' },
        advantage: 'Kiểm thử feature mới dưới tải thực tế mà không gây ảnh hưởng đến người dùng.',
      },
      flowSteps: [
        { stepNumber: 1, title: 'Sub-5ms Flag Evaluation', description: 'Đọc quy tắc flag từ Redis cache: feature:flag:<name>', component: 'Redis Cache' },
        { stepNumber: 2, title: 'Consistent Hashing Bucket', description: 'Băm userId % 100 để xác định % Canary Rollout', component: 'Canary Evaluator' },
        { stepNumber: 3, title: 'Fire-and-Forget Shadow Mirror', description: 'Nhân bản async payload sang Service V2 ngầm qua setImmediate()', component: 'Shadow Traffic Mirror' },
      ],
      benchmarkResult: {
        naiveMetric: 'Redeploy Required for Any Toggle',
        optimizedMetric: 'Sub-5ms Dynamic Toggle + 0ms User Latency Overhead for Shadow Traffic',
        improvement: 'Zero Downtime Canary & Dark Launching',
      },
      curlSnippet: 'curl -X POST http://localhost:3000/api/v1/traffic-engineering/optimized/evaluate -H "Content-Type: application/json" -d \'{"flagName":"NEW_CHECKOUT_V2","userId":"USER_5521"}\'',
    },
    {
      id: 'file-stream-processing',
      phase: 'Phase 4',
      moduleCode: 'module-4.2',
      title: 'High-Performance Stream File Processing (< 30MB RAM)',
      badge: 'Stream Processing',
      overview: 'Xử lý file CSV/Excel dung lượng lớn (hàng triệu dòng) bằng Node.js Stream Pipeline Backpressure, giữ RAM tiêu thụ cố định < 30 MB.',
      naiveStrategy: {
        description: 'Đọc toàn bộ file vào V8 RAM Buffer cùng lúc bằng `fs.readFileSync()`.',
        endpoint: '/api/v1/file-streaming/naive/upload',
        method: 'POST',
        samplePayload: { filepath: 'sample_large_dataset.csv' },
        drawback: 'Tốn hàng trăm Megabyte RAM, gây văng lỗi `HEAP OUT OF MEMORY (OOM)`.',
      },
      optimizedStrategy: {
        description: 'Sử dụng `fs.createReadStream()` kết hợp `readline` đọc theo từng dòng và gom batch 1,000 bản ghi/lượt với cơ chế Backpressure.',
        endpoint: '/api/v1/file-streaming/optimized/stream-upload',
        method: 'POST',
        samplePayload: { filepath: 'sample_large_dataset.csv', batchSize: 1000 },
        advantage: 'Bộ nhớ RAM luôn giữ ổn định < 30 MB bất kể file kích thước vài Gigabyte.',
      },
      flowSteps: [
        { stepNumber: 1, title: 'Create Readable Stream', description: 'Mở stream đọc tệp fs.createReadStream(path)', component: 'Node.js FS Stream' },
        { stepNumber: 2, title: 'Line-by-Line Readline', description: 'Đọc từng dòng qua readline interface', component: 'Readline Engine' },
        { stepNumber: 3, title: 'Batch Buffer Drain', description: 'Gom batch 1,000 bản ghi và tạm dừng stream khi buffer đầy (Backpressure Drain)', component: 'Stream Backpressure Guard' },
        { stepNumber: 4, title: 'Chunked Response Export', description: 'Xuất CSV trực tiếp qua HTTP Chunked Response (Transfer-Encoding: chunked)', component: 'Express Chunked Response' },
      ],
      benchmarkResult: {
        naiveMetric: 'RAM Bloat (> 500 MB RAM / OOM Crash)',
        optimizedMetric: '< 30 MB RAM Constant Footprint',
        improvement: '93.3% Faster & Zero OOM Risk',
      },
      curlSnippet: 'curl -X POST http://localhost:3000/api/v1/file-streaming/optimized/stream-upload -H "Content-Type: application/json" -d \'{"filepath":"sample_large_dataset.csv","batchSize":1000}\'',
    },
  ];

  getAllModulesDoc(): SystemModuleDoc[] {
    return this.modulesDoc;
  }

  getModuleDocById(id: string): SystemModuleDoc | undefined {
    return this.modulesDoc.find((m) => m.id === id || m.moduleCode === id);
  }
}
